name = "gwr"
version = "0.0.2"
description = "An experimental work-in-progress (WIP) WebAssembly runtime written in Gleam."
licences = ["MIT"]
repository = { type = "github", user = "BrendoCosta", repo = "gwr" }

[dependencies]
gleam_stdlib = ">= 0.54.0 and < 2.0.0"
gleb128 = ">= 2.1.1 and < 3.0.0"
ieee_float = ">= 1.2.0 and < 2.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.3.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
