name: release

on:
  push:
    branches:
      - main

env:
  GLEAM_VERSION: "1.12.0"
  OTP_VERSION: "28.1"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Setup OTP and Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          gleam-version: "${{ env.GLEAM_VERSION }}"
      
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.4.1
        with:
          ref: ${{ github.sha }}
          check-name: Run tests
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 5

      - name: Semantic release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v5
        with:
          extra_plugins: "@semantic-release/exec"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Hex package manager
        if: steps.semantic-release.outputs.new_release_published == 'true'
        env:
          HEXPM_API_KEY: ${{ secrets.HEXPM_API_KEY }}
        run: gleam publish --yes