name: tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - dev
  schedule:
    - cron: 00 10 * * 3
env:
  GLEAM_VERSION: "1.9.1"
  OTP_VERSION: "27.3"
jobs:
  amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          gleam-version: "${{ env.GLEAM_VERSION }}"
      - name: Check source code formatting
        run: gleam format --check
      - name: Install build dependencies
        run: sudo apt-get -y install make podman
      - name: Download dependencies
        run: gleam deps download
      - name: Update dependencies
        run: gleam update
      - name: Run tests (Erlang)
        run: make test